openapi: 3.2.0
info:
  title: Bookkeeping & Invoicing/eAccounting API V2 Article Labels…
  description: 'Visit our complete Bookkeeping & Invoicing/eAccounting API docs for how to get started, information about authentication, error handling, query customization and more.


    ✉ API Support'
  version: v2
servers:
- url: https://eaccountingapi.vismaonline.com/v2/
tags:
- name: ArticleLabels
  description: 'Groups used to categorise and organise the articles.

    Overview of Article Labels Functionality: Article labels


    ___


    Available in any of the following variants:

    * Pro

    * Standard

    * Invoicing'
paths:
  /articlelabels:
    get:
      tags:
      - ArticleLabels
      summary: Gets all article labels
      description: 'Get all article labels, or add query parameters to filter the results. The response will include a list of article labels with their details, such as name and description information.


        ___

        Requires any of the following scopes:

        * ea:sales

        * ea:sales_readonly'
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedResponseOfArticleLabelApi'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonExtendedBadRequest'
      operationId: getArticlelabels
      x-operation-id-source: derived
    post:
      tags:
      - ArticleLabels
      summary: Create an article label
      description: 'Create a new article label.


        ___

        Requires any of the following scopes:

        * ea:sales'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleLabelApi'
      responses:
        '201':
          description: The created article label
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleLabelApi'
        '400':
          description: The article label can't be created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonExtendedBadRequest'
      operationId: postArticlelabels
      x-operation-id-source: derived
  /articlelabels/{articlelabelid}:
    get:
      tags:
      - ArticleLabels
      summary: Gets an article label by id
      description: 'Get a specific article label by its unique identifier. The response will contain the aricle label''s details, including the article''s name and description information.


        ___

        Requires any of the following scopes:

        * ea:sales

        * ea:sales_readonly'
      parameters:
      - name: articleLabelId
        in: path
        description: This represents the Id of the article label.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleLabelApi'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonExtendedBadRequest'
      operationId: getArticlelabelsByArticlelabelid
      x-operation-id-source: derived
  /articlelabels/{articleLabelId}:
    put:
      tags:
      - ArticleLabels
      summary: Replace an article label
      description: 'Replace an existing article label''s data with the provided new data. The article label must already exist in the system.


        ___

        Requires any of the following scopes:

        * ea:sales'
      parameters:
      - name: articleLabelId
        in: path
        description: This represents the Id of the article label
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleLabelApi'
      responses:
        '200':
          description: The updated article label
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleLabelApi'
        '400':
          description: The article label can't be updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonExtendedBadRequest'
      operationId: putArticlelabelsByArticleLabelId
      x-operation-id-source: derived
    delete:
      tags:
      - ArticleLabels
      summary: Delete an article label
      description: 'Deletes a specified article label.


        ___

        Requires any of the following scopes:

        * ea:sales'
      parameters:
      - name: articleLabelId
        in: path
        description: This represents the Id of the article label
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Request successful
        '404':
          description: Article label not found
        '400':
          description: Article label can't be deleted
      operationId: deleteArticlelabelsByArticleLabelId
      x-operation-id-source: derived
components:
  schemas:
    CommonPaginationMetadata:
      required:
      - CurrentPage
      - PageSize
      - ServerTimeUtc
      - TotalNumberOfPages
      - TotalNumberOfResults
      type: object
      properties:
        CurrentPage:
          type: integer
          description: The current page number
          format: int32
        PageSize:
          type: integer
          description: The number of results per page
          format: int32
        TotalNumberOfPages:
          type: integer
          description: The total number of pages available
          format: int32
        TotalNumberOfResults:
          type: integer
          description: The total number of results available for the query
          format: int32
        ServerTimeUtc:
          type: string
          description: <strong>Possible values:</strong><br/>2017-07-21T17:32:28Z<br/><br/>The date-time notation as defined by RFC 3339, section 5.6.
          format: date-time
      additionalProperties: false
    PaginatedResponseOfArticleLabelApi:
      required:
      - Data
      - Meta
      type: object
      properties:
        Meta:
          $ref: '#/components/schemas/CommonPaginationMetadata'
        Data:
          type: array
          items:
            $ref: '#/components/schemas/ArticleLabelApi'
      additionalProperties: false
    CommonError:
      type: object
      properties:
        Field:
          type:
          - string
          - 'null'
        ErrorCode:
          type:
          - string
          - 'null'
        Message:
          type:
          - string
          - 'null'
        Key:
          type:
          - string
          - 'null'
      additionalProperties: false
    ArticleLabelApi:
      required:
      - Name
      type: object
      properties:
        Id:
          type: string
          description: Unique Id provided by the system
          format: uuid
          readOnly: true
        Name:
          maxLength: 50
          minLength: 0
          type: string
          description: Name of the article label
        Description:
          maxLength: 400
          minLength: 0
          type:
          - string
          - 'null'
          description: Description of the article label
      additionalProperties: false
    CommonExtendedBadRequest:
      type: object
      properties:
        ErrorCode:
          type: integer
          format: int32
        DeveloperErrorMessage:
          type:
          - string
          - 'null'
        ErrorId:
          type: string
          format: uuid
        Errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/CommonError'
      additionalProperties: false
x-tagGroups:
- name: Sales
  tags:
  - ArticleLabels
  - Articles
  - CustomerInvoiceDrafts
  - CustomerInvoiceOffsets
  - CustomerInvoices
  - CustomerInvoiceValuationHistories
  - CustomerLabels
  - CustomerLedgerItems
  - Customers
  - DeliveryMethods
  - DeliveryTerms
  - DiscountAgreements
  - Orders
  - QuoteDrafts
  - Quotes
  - SalesPriceLists
  - TermsOfPayment
  - WebshopOrders
- name: Purchase
  tags:
  - BankAccounts
  - ForeignPaymentCodes
  - PurchaseReceiptDrafts
  - SupplierInvoiceDrafts
  - SupplierInvoices
  - SupplierInvoiceValuationHistories
  - SupplierLedgerItems
  - Suppliers
- name: Common
  tags:
  - Approval
  - AppStoreActivationStatus
  - AttachmentLinks
  - Attachments
  - AutoInvoice
  - Bank
  - Charts
  - CompanySettings
  - Company
  - Countries
  - Currencies
  - Documents
  - IdentityLookup
  - MessageThreads
  - Mobile
  - Notes
  - PartnerResourceLinks
  - SalesDocumentAttachments
  - Trials
  - Units
  - Users
  - VoTokenValidation
  - WebHooks
  - Zapier
- name: Accounting
  tags:
  - AccountBalance
  - Accounts
  - AccountTypes
  - AllocationPeriods
  - ArticleAccountCodings
  - BankTransactions
  - CostCenterItems
  - CostCenters
  - FiscalYears
  - InventoryItems
  - PaymentVoucher
  - Projects
  - SieFileImportExport
  - VatCode
  - VatReport
  - VoucherDrafts
  - Vouchers
  - VoucherWithOverunderPayment
